set(_CATKIN_CURRENT_PACKAGE "visualization")
set(visualization_VERSION "0.0.0")
set(visualization_MAINTAINER "xuxiaowei <xuxiaowei@todo.todo>")
set(visualization_PACKAGE_FORMAT "2")
set(visualization_BUILD_DEPENDS "rospy" "rviz")
set(visualization_BUILD_EXPORT_DEPENDS "rospy" "rviz")
set(visualization_BUILDTOOL_DEPENDS "catkin")
set(visualization_BUILDTOOL_EXPORT_DEPENDS )
set(visualization_EXEC_DEPENDS "rospy" "rviz")
set(visualization_RUN_DEPENDS "rospy" "rviz")
set(visualization_TEST_DEPENDS )
set(visualization_DOC_DEPENDS )
set(visualization_URL_WEBSITE "")
set(visualization_URL_BUGTRACKER "")
set(visualization_URL_REPOSITORY "")
set(visualization_DEPRECATED "")